# Generated by Django 4.2 on 2023-04-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date_Users',
            new_name='Date_User',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
